name: Deploy

on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_REGION: us-east-1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npx eslint .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test

  synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npx cdk synth

  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_DEV_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - run: npx cdk diff

  deploy-dev:
    runs-on: ubuntu-latest
    needs: [lint, test, synth, diff]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_DEV_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - run: npx cdk deploy --require-approval never

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: ${{ steps.deploy-prod.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_PROD_OIDC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - run: npx cdk deploy --require-approval never
